

INSERT INTO "doh_positions" ("pos_desc") VALUES
('1. Consultants'),
('1.1 Internal Medicine'),
('a. Generalist'),
('b. Cardiologist'),
('c. Endocrinologist'),
('d. Gastro-Enterologist'),
('e. Pulmonologist'),
('f. Nephrologist'),
('g. Neurologist'),
('1.2. Obstetrics/ Gynecology (and sub-specialty)'),
('1.3. Pediatrics (and sub-specialty)'),
('1.4. Surgery (and sub-specialty)'),
('1.5. Anesthesiologist'),
('1.6. Radiologist'),
('1.7. Pathologist'),
('2. Post-Graduate Fellows<br>(Indicate specialty/subspecialty)'),
('3. Residents'),
('3.1. Internal Medicine'),
('3.2. Obstetricts-Gynecology'),
('3.3. Pediatrics'),
('3.4. Surgery'),
('1. Nurses'),
('2. Midwives'),
('3. Nursing Aides'),
('4. Nutritionist'),
('5. Physical Therapist'),
('6. Pharmacists'),
('7. Medical Technologist'),
('8. Laboratory Technician'),
('9. X-Ray Technologist/X-Ray Technician'),
('10. Medical Equipment Technician'),
('11. Social Worker'),
('12. Medical Records Officer/ Hospital Health Information Officer'),
('1. Chief Administrative Officer'),
('2. Accountant'),
('3. Budget officer'),
('4. Cashier'),
('5. Clerk'),
('6. Engineer'),
('7. Driver'),
('9. General Support Staff'),
('Janitorial'),
('Maintenance'),
('Security');
