

INSERT INTO "permissions" ("permission_id", "module_id") VALUES
('dashboard', 'dashboard'),
('inventory', 'inventory'),
('queue', 'queue'),
('patients', 'patients'),  
('out-patient', 'out-patient'),  
('in-patient', 'in-patient'),
('obgyne', 'obgyne'),
('pediatric', 'pediatric'),
('telumed', 'telumed'),
('emergency-room', 'emergency-room'),
('pharmacy', 'pharmacy'),
('eye-center', 'eye-center'),
('dietary', 'dietary'),
('imaging', 'imaging'),
('laboratory', 'laboratory'),
('billing', 'billing'),
('human-resource', 'human-resource'),
('employee', 'employee'),
('doctor', 'doctor'),
('payroll', 'payroll'),
('employee-request', 'employee-request'),
('materials', 'materials'),
('supplier', 'supplier'),
('purchase-order', 'purchase-order'),
('delivery', 'delivery'),
('donations', 'donations'),
('stock-request', 'stock-request'),
('settings',	'settings'),
('system',	'system'),
('hr',	'hr'),
('charges',	'charges'),
('bed',	'bed'),
('symptoms',	'symptoms'),
('pharmacy-config',	'pharmacy-config'),
('panthology',	'panthology'),
('radiology',	'radiology'),
('doh-report',	'doh-report');


-- ('certificate',	'certificate'),
-- ('item-stock',	'item-stock'),
-- ('bed-management', 'bed-management'),
-- ('diagnosis', 'diagnosis'),
-- ('enquiries', 'enquiries'),
-- ('front-office', 'front-office'),
-- ('radiology', 'radiology'),
-- ('tpa-management', 'tpa-management'),
-- ('finance',  'finance'),
-- ('ambulance',  'ambulance'),
-- ('certificate-record', 'certificate-record'),
-- ('item', 'item'),
-- ('issue-item', 'issue-item'),
-- ('appointments', 'appointments');