INSERT INTO "symptoms" ("code","name", "created_at", "updated_at") VALUES
('altmentsens', 'Altered mental sensorium', now(), now()),
('abdcrmp', 'Abdominal cramp/pain', now(), now()),
('anrx', 'Anorexia', now(), now()),
('bldgums', 'Bleeding gums', now(), now()),
('bodywkn', 'Body weakness', now(), now()),
('blrofvis', 'Blurring of vision', now(), now()),
('chestpndisc', 'Chest pain/discomfort', now(), now()),
('constpn', 'Constipation', now(), now()),
('cuf', 'Cough', now(), now()),
('drhea', 'Diarrhea', now(), now()),
('dzness', 'Dizziness',now(), now()),
('dysphg', 'Dysphagia',now(), now()),
('dyspn', 'Dyspnea', now(), now()),
('dysur', 'Dysuria', now(), now()),
('epstxs', 'Epistaxis', now(), now()),
('fver', 'Fever', now(), now()),
('freqofuri', 'Frequency of urination', now(), now()),
('hdache', 'Headache', now(), now()),
('hmtemsis', 'Hematemesis', now(), now()),
('hmtur', 'Hematuria', now(), now()),
('hmptys', 'Hemoptysis', now(), now()),
('irtblty', 'Irritability', now(), now()),
('jndc', 'Jaundice', now(), now()),
('lowexedm', 'Lower extremity edema', now(), now()),
('mylg', 'Myalgia', now(), now()),
('orthpn', 'Orthopnea', now(), now()),
('pain', 'Pain', now(), now()),
('palptns', 'Palpitations', now(), now()),
('szrs', 'Seizures', now(), now()),
('srash', 'Skin rashes', now(), now()),
('stoolbbm', 'Stool, bloody/black/mucoid', now(), now()),
('swtng', 'Sweating', now(), now()),
('urgn', 'Urgency', now(), now()),
('vmtng', 'Vomiting', now(), now()),
('wloss', 'Weight loss', now(), now()),
('others', 'Others', now(), now());